# -*- coding: utf-8 -*-
"""LAB PRACTICAL-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ylvE48Ea-Wgzw3faCejlYFPwOel8IJAy

Practical-1

SELECTION SORT
"""

import time

def selection_sort(arr):
    n = len(arr)

    for i in range(n - 1):
        min_index = i

        for j in range(i + 1, n):
            if arr[j] < arr[min_index]:
                min_index = j

        # Swap the minimum element with the current element
        arr[i], arr[min_index] = arr[min_index], arr[i]


# User Input
n = int(input("Enter the number of elements: "))

arr = []
print("Enter the elements:")
for i in range(n):
    arr.append(int(input()))

# Measure execution time
start_time = time.perf_counter()

selection_sort(arr)

end_time = time.perf_counter()

execution_time = end_time - start_time

# Display sorted array
print("\nSorted Array:")
print(arr)

# Display execution time
print(f"\nExecution Time: {execution_time:.10f} seconds")

# Display time complexity
print("\nTime Complexity:")
print("Best Case    : O(n²)")
print("Average Case : O(n²)")
print("Worst Case   : O(n²)")

# Display space complexity
print("\nSpace Complexity: O(1)")

"""2.MERGE SORT"""

import time

def merge(arr, left, mid, right):
    n1 = mid - left + 1
    n2 = right - mid

    L = arr[left:left + n1]
    R = arr[mid + 1:mid + 1 + n2]

    i = 0
    j = 0
    k = left

    while i < n1 and j < n2:
        if L[i] <= R[j]:
            arr[k] = L[i]
            i += 1
        else:
            arr[k] = R[j]
            j += 1
        k += 1

    while i < n1:
        arr[k] = L[i]
        i += 1
        k += 1

    while j < n2:
        arr[k] = R[j]
        j += 1
        k += 1


def merge_sort(arr, left, right):
    if left < right:
        mid = (left + right) // 2

        merge_sort(arr, left, mid)
        merge_sort(arr, mid + 1, right)

        merge(arr, left, mid, right)


# User Input
n = int(input("Enter the number of elements: "))

print("Enter the elements separated by spaces:")
arr = list(map(int, input().split()))

# Check number of elements
if len(arr) != n:
    print(f"Error: Please enter exactly {n} elements.")
    exit()

# Measure execution time
start_time = time.perf_counter()

merge_sort(arr, 0, n - 1)

end_time = time.perf_counter()

execution_time = end_time - start_time


# Output
print("\nSorted Array:")
print(arr)

print(f"\nExecution Time: {execution_time:.10f} seconds")

print("\nTime Complexity:")
print("Best Case    : O(n log n)")
print("Average Case : O(n log n)")
print("Worst Case   : O(n log n)")

print("\nSpace Complexity: O(n)")

"""3.BUBBLE SORT"""

import time

def bubble_sort(arr):
    n = len(arr)

    for i in range(n - 1):
        swapped = False

        for j in range(0, n - i - 1):
            if arr[j] > arr[j + 1]:
                # Swap elements
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
                swapped = True

        # If no swapping occurred, array is already sorted
        if not swapped:
            break


# User Input
n = int(input("Enter the number of elements: "))

print("Enter the elements separated by spaces:")
arr = list(map(int, input().split()))

# Check number of elements
if len(arr) != n:
    print(f"Error: Please enter exactly {n} elements.")
    exit()

# Measure execution time
start_time = time.perf_counter()

bubble_sort(arr)

end_time = time.perf_counter()

execution_time = end_time - start_time


# Output
print("\nSorted Array:")
print(arr)

print(f"\nExecution Time: {execution_time:.10f} seconds")

print("\nTime Complexity:")
print("Best Case    : O(n)")
print("Average Case : O(n²)")
print("Worst Case   : O(n²)")

print("\nSpace Complexity: O(1)")

"""INSERTION SORT"""

import time

def insertion_sort(arr):
    n = len(arr)

    for i in range(1, n):
        key = arr[i]
        j = i - 1

        # Move elements greater than key one position ahead
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j = j - 1

        arr[j + 1] = key


# User Input
n = int(input("Enter the number of elements: "))

print("Enter the elements separated by spaces:")
arr = list(map(int, input().split()))

# Check number of elements
if len(arr) != n:
    print(f"Error: Please enter exactly {n} elements.")
    exit()

# Measure execution time
start_time = time.perf_counter()

insertion_sort(arr)

end_time = time.perf_counter()

execution_time = end_time - start_time


# Output
print("\nSorted Array:")
print(arr)

print(f"\nExecution Time: {execution_time:.10f} seconds")

print("\nTime Complexity:")
print("Best Case    : O(n)")
print("Average Case : O(n²)")
print("Worst Case   : O(n²)")

print("\nSpace Complexity: O(1)")

"""5.QUICK SORT"""

import time

def partition(arr, low, high):
    # Choosing last element as pivot
    pivot = arr[high]

    i = low - 1

    for j in range(low, high):
        if arr[j] <= pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]

    arr[i + 1], arr[high] = arr[high], arr[i + 1]

    return i + 1


def quick_sort(arr, low, high):
    if low < high:
        # Find partition index
        pi = partition(arr, low, high)

        # Sort left and right parts
        quick_sort(arr, low, pi - 1)
        quick_sort(arr, pi + 1, high)


# User Input
n = int(input("Enter the number of elements: "))

print("Enter the elements separated by spaces:")
arr = list(map(int, input().split()))

# Check number of elements
if len(arr) != n:
    print(f"Error: Please enter exactly {n} elements.")
    exit()


# Measure execution time
start_time = time.perf_counter()

quick_sort(arr, 0, n - 1)

end_time = time.perf_counter()

execution_time = end_time - start_time


# Output
print("\nSorted Array:")
print(arr)

print(f"\nExecution Time: {execution_time:.10f} seconds")

print("\nTime Complexity:")
print("Best Case    : O(n log n)")
print("Average Case : O(n log n)")
print("Worst Case   : O(n²)")

print("\nSpace Complexity: O(log n)")