# -*- coding: utf-8 -*-
"""PRACTICAL 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mM92UZRcYVXdew2mfvoCJ64x8kVtqlKZ
"""

import time

# Max Heapify
def heapify(arr, n, i):
    largest = i
    left = 2 * i + 1
    right = 2 * i + 2

    # Check left child
    if left < n and arr[left] > arr[largest]:
        largest = left

    # Check right child
    if right < n and arr[right] > arr[largest]:
        largest = right

    # If largest is not the root
    if largest != i:
        arr[i], arr[largest] = arr[largest], arr[i]

        # Heapify the affected subtree
        heapify(arr, n, largest)


# Max Heap Sort
def heap_sort(arr):
    n = len(arr)

    # Build Max Heap
    for i in range(n // 2 - 1, -1, -1):
        heapify(arr, n, i)

    # Extract elements one by one
    for i in range(n - 1, 0, -1):
        arr[0], arr[i] = arr[i], arr[0]
        heapify(arr, i, 0)


# ---------------- INPUT ----------------
start_input = time.perf_counter()

arr = list(map(int, input(
    "Enter elements separated by spaces: "
).split()))

end_input = time.perf_counter()

input_time = end_input - start_input


# ---------------- SORTING ----------------
start_sort = time.perf_counter()

heap_sort(arr)

end_sort = time.perf_counter()

execution_time = end_sort - start_sort


# ---------------- OUTPUT ----------------
print("\nOriginal/Sorted Result:")
print("Sorted array:", arr)

print("\n========== COMPLEXITY ==========")

print("Input Time Complexity       : O(n)")
print("Best Case Time Complexity   : O(n log n)")
print("Average Case Time Complexity: O(n log n)")
print("Worst Case Time Complexity  : O(n log n)")
print("Space Complexity            : O(log n)")

print("\n========== EXECUTION TIME ==========")
print("Input Execution Time        :",
      format(input_time, ".10f"), "seconds")

print("Sorting Execution Time      :",
      format(execution_time, ".10f"), "seconds")